version: '3.7'

services:
#  php:
#    build:
#      dockerfile: docker/dev/php/Dockerfile
#      context: .
#    platform: linux/x86_64
#    container_name: deck-php
#    expose:
#      - 80
#    ports:
#      - "8888:80"
#    volumes:
#      - .:/var/www/deck
#    working_dir: /var/www/deck
#    links:
#      - postgresql
#    environment:
#      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
#      PHP_IDE_CONFIG: 'serverName=Dev'
#      XDEBUG_REMOTE_HOST: 'docker.for.mac.host.internal'
#
  postgresql:
    image: postgres:9.6.6
    container_name: pact-database
    expose:
      - 5433
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=pact
    volumes:
      - database:/var/lib/postgresql/data


  api-doc:
    image: swaggerapi/swagger-ui:v3.52.3
    container_name: pact-swagger
    restart: unless-stopped
    expose:
      - 8001
    ports:
      - "8001:8080"
    environment: [ "SWAGGER_JSON=/var/www/web/openapi_v3.yml","VALIDATOR_URL=" ]
    volumes:
      - ./spec:/var/www/web:ro

  pact-broker:
    image: 'pactfoundation/pact-broker:latest'
    platform: linux/x86_64
    container_name: pact-broker
    depends_on:
      - postgresql
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_DATABASE_URL: 'postgres://admin:pass@postgresql/pact'
      PACT_BROKER_PORT: '9292'
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_SQL_LOG_LEVEL: DEBUG
      # PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES is only needed for docker-compose
      # because the database takes longer to start up than the puma process
      # Should not be needed in production.
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
      # The list of allowed base URLs (not setting this makes the app vulnerable to cache poisoning)
      # This allows the app to be addressed from the host from within another docker container correctly
      PACT_BROKER_BASE_URL: 'https://localhost http://localhost http://localhost:9292 http://deck-pact-broker:9292'

volumes:
  database:
    driver: local
