---
openapi: 3.0.3
info:
  version: 1.0.0
  title: Product API
  contact:
    email: javieroman@gmail.com
  description: Product API OpenAPI 3.0.3 definition
servers:
  - url: http://localhost:8000
components:
  schemas:
    product:
      title: Product
      type: object
      required:
        - id
        - sku
        - price
        - currency
        - slug
        - published
      properties:
        id:
          type: string
          format: uuid
        sku:
          type: string
        price:
          type: number
          format: float
        currency:
          type: string
        slug:
          type: string
        published:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      example:
        id: "e7ba4c75-b1bb-483d-94d8-2c4a10f78472"
        sku: "556312"
        price: 49.99
        currency: "€"
        slug: "lagavulin-16-years"
        published: true
        createdAt: "1970-01-01T00:00:00.001Z"
        updatedAt: "1970-01-01T00:00:00.001Z"
paths:
  '/product':
    get:
      operationId: get-product
      description: Get a product
      responses:
        '200':
          description: Get a product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product"


